# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "cpanvote"

# The default layout to use for your application (located in
# views/layouts/main.tt)
#layout: "main"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

template: "mason"

session: cookie
session_cookie_key: sfdfaifbbbf#$%#$4njdfjdfkgbdfbd

plugins:
    "Auth::Twitter":
        consumer_key:     "Bfco4J8hvOIWcd0NmpRog"
        consumer_secret:  "secret"
        callback_url:     http://enkidu:3000/auth/twitter/callback
        callback_success: /welcome
    DBIC:
        cpanvote:
            schema_class: cpanvote::Schema
            dsn:  "dbi:SQLite:dbname=./database.db"
